### ISSUE TITLE
Item ID expansion

### ISSUE THREAD

**Issue by TiberDasher** [janxious/InternalHeaters#2]
Issue:  IH only looks for the Item ID of the stock DHS.

If an option were added which allow for different/additional item ID a single slot CT item, weighing 0 tons and no dissipation on its own, could be created to trigger the DHS effect.

This would be beneficial for builds which do not require additional heatsinks, beyond the ones which come with the engine.

**Comment by janxious** [comment]
My insomnia is your bonus! https://github.com/janxious/InternalHeaters/releases/tag/v0.0.11
