### ISSUE TITLE
Multiple items to trigger DHS effect

### ISSUE THREAD

**Issue by TiberDasher** [janxious/InternalHeaters#3]
Having to use a DHS to trigger the DHS effect may "waste" critical slots and tonnage when the build only needs to dissipate 31-60 heat/turn. With the option to set multiple items to trigger the DHS effect a 1 slot/0 ton item could be added to the list which could then be used to trigger the DHS effect in cases where 31-60 heat/turn dissipation, provided by the engine equipped DHS, is needed (saving two crit slots and one ton). 

An example of a mech which requires only ten double heat sinks is the HGN-732b; With the proposed change (add ability to specify multiple trigger items, concurrently) the 732b acquired through the campaign could be made into a true 732b, at least as far as heat dissipation is concerned, with out using too many critical slots. Also, 733's could be made into 732b's in this same fashion.

**Comment by janxious** [comment]
So in this example you would have normal DHS in addition to a new item I'll call ⚡️. I equip one ⚡️ and 3 DHS, and I get 30 base+30 doubled+18 DHS dissipation?

**Comment by TiberDasher** [comment]
The new item wouldn't be required if there were normal double heat sinks in the build, but in cases where only the ten engine DHS are required you would use the new item in order to gain the +30.

**Comment by Ruffyen** [comment]
Hi!  I love this mod!

I am not sure if this should be a new topic/issue so I will just put it here.

The "Battletech Enhanced" mod I installed adds a DHS called "Gear_HeatSink_Generic_Double_EX".
How would I get that added to your mod.json?

Specifically the line in settings that says:
"doubleHeatSinksDoubleEngineHeatDissipationComponentId": "Gear_HeatSink_Generic_Double"
How do I get both to be recognized as double heat sinks?

Thanks in advance!

**Comment by janxious** [comment]
This is the issue for that! I have not written the code to do it. The short version is [this code](https://github.com/janxious/InternalHeaters/blob/master/InternalHeaters.cs#L35-L57) will need to be able to deal with a list of values, and the settings file will need to be able to take an array of values.

You could replace the value if you don't intend to use the vanilla double heat sinks.

**Comment by Ruffyen** [comment]
Yeah that sounds like what I was hoping for (an _array_ where things like heat exchangers and heat banks could be added so they don't mess up the double engine heat sinks).

This is a wonderful mod I really love it! 
Looking forward to that array. I will keep my eyes on this topic for further news.

Thanks janxious!

**Comment by janxious** [comment]
@Ruffyen @TiberDasher [v1.0.0](https://github.com/janxious/InternalHeaters/releases/tag/v1.0.0) includes the functionality you requested. Cheers!

**Comment by TiberDasher** [comment]
Thanks Janxious, you da man.

Sent from my Verizon 4G LTE Droid
On Jul 18, 2018 17:12, janxious <notifications@github.com> wrote:

@Ruffyen<https://github.com/Ruffyen> @TiberDasher<https://github.com/TiberDasher> v1.0.0<https://github.com/janxious/InternalHeaters/releases/tag/v1.0.0> includes the functionality you requested. Cheers!
